#!/bin/bash

# edac-util RAM error detection
# 
# (c) 2014, Tom Laermans for Observium

# Dependencies: edac-utils
# Debian/Ubuntu: apt-get install edac-utils
# RHEL/CentOS: yum install edac-utils

edacutil=`which edac-util`

if [ $? -eq 0 ];
then
  echo '<<<edac>>>'
  $edacutil -v
fi
