#!/bin/bash

mongostat=$(command -v mongostat)
if [ -x "$mongostat" ]; then

    user="${MONGO_USER:-}"
    password="${MONGO_PASSWORD:-}"
    port="${MONGO_PORT:-27017}"
    ad="${MONGO_AUTH_DB:-admin}"

    echo '<<<app-mongodb>>>'
    "${mongostat}" -u "$user" -p "$password" --port "$port" --authenticationDatabase "$ad" --humanReadable false --noheaders -n 1 1 --json
fi